# Generated by Django 6.0.3 on 2026-04-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_tablebooking_meal_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablebooking",
            name="meal_time",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast:6:30 a.m. - 9:00 a.m."),
                    ("Lunch", "Lunch:11:00 a.m. - 1:00 p.m."),
                    ("Dinner", "Dinner:5:00 p.m. - 7:00 p.m."),
                ],
                default="Breakfast",
                max_length=50,
            ),
        ),
    ]
