# Generated by Django 6.0.3 on 2026-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tablebooking_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='category',
            field=models.CharField(choices=[('Canteen', 'Canteen & Dining'), ('Room', 'Room & Booking'), ('Equipment', 'Equipment')], default='Equipment', max_length=20),
        ),
    ]
