# Generated by Django 6.0.3 on 2026-04-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_issuereport_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipment'),
        ),
    ]
